language: python
dist: trusty
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"
    - "pypy"
    - "pypy3"
matrix:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
install: "pip install -e .[test]"
script: make test
before_install:
    # Coverage 4.0 no longer supports py3.2 and codecov depends on latest coverage
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install "coverage<4.0dev"; fi
    - pip install codecov
after_success:
    - codecov
notifications:
    slack: raspberrypifoundation:YoIHtVdg8Hd6gcA09QEmCYXN
